@startwbs 見積宴会システム
title 八幡平ハイツ見積宴会システムWBS
* 見積管理アプリ
**[#SkyBlue] 画面を作る
***[#Yellow] 名前入力テキストボックス
***[#Yellow] 宿泊日程プルダウン
***[#Yellow] 部屋グレードラジオボタン
***[#Yellow] 人数プルダウン
***[#Yellow] 飲み放題チェックボックス
***[#Yellow] 追加料理チェックボックス
***[#Yellow] 二次会チェックボックス
***[#Yellow] 見積ボタン
***[#Yellow] 確定ボタン
**[#SkyBlue] 見積計算ボタン
***[#Yellow] オプションに応じて追加料金を計算
***[#Yellow] グレードや人数に応じて料金プラス
***[#Yellow] 基本料金の合計を出す
**[#SkyBlue] 確定ボタン
***[#Yellow] 名前と見積もった料金がメールに来る

@endwbs