@startwbs 見積システム
title 八幡平ハイツ見積システムWBS
* 見積管理アプリ
**[#SkyBlue] 選択メニュー画面
***[#Yellow] 宿泊コース選択ラジオボタン
***[#Yellow] 宴会コース選択ラジオボタン
**[#SkyBlue] 宿泊見積作成画面
***[#Yellow] 名前入力テキストボックス
***[#Yellow] 宿泊日程プルダウン
***[#Yellow] 部屋タイプラジオボタン
***[#Yellow] 人数プルダウン
***[#Yellow] 夕食プランラジオボタン
***[#Yellow] 早割の適用有無ラジオボタン
***[#Yellow] 見積もり計算ボタン
***[#Yellow] 確定ボタン
**[#SkyBlue] 宴会見積作成画面
***[#Yellow] 名前入力テキストボックス
***[#Yellow] 宿泊日程プルダウン
***[#Yellow] 部屋グレードラジオボタン
***[#Yellow] 人数プルダウン
***[#Yellow] 飲み放題チェックボックス
***[#Yellow] 追加料理チェックボックス
***[#Yellow] 二次会チェックボックス
***[#Yellow] 見積ボタン
***[#Yellow] 確定ボタン
**[#SkyBlue] 見積送信完了画面
***[#Yellow] 見積もりの小計を出力
***[#Yellow] 名前と見積もった料金がメールに来る
@endwbs