@startwbs 見積宿泊システム
title 八幡平ハイツ見積宿泊システムWBS
* 見積管理アプリ
**[#SkyBlue] 画面を作る
***[#Yellow] 名前入力テキストボックス
***[#Yellow] 宿泊日程プルダウン
***[#Yellow] 部屋タイプラジオボタン
***[#Yellow] 人数プルダウン
***[#Yellow] 夕食プランラジオボタン
***[#Yellow] 早割の適用有無ラジオボタン
***[#Yellow] 見積もり計算ボタン
***[#Yellow] 確定ボタン
**[#SkyBlue] 見積計算ボタン
***[#Yellow] 土曜日の時通常料金にプラスして計算
***[#Yellow] 早割（60日10%、90日15%）の割引
***[#Yellow] 基本料金の合計を出す
***[#Yellow] 日程や人数に応じて料金プラス
**[#SkyBlue] 確定ボタン
***[#Yellow] 名前と見積もった料金がメールに来る

@endwbs